eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 8140
spring:
  application:
    name: zuul-router
zuul:
  routes:
    api-a:
      path: /record/**
      serviceId: user-service
  socket-timeout-millis: 60000
  connect-timeout-millis: 60000