server:
  port: 8180
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

spring:
  application:
    name: dynamic-datasources



##多数据源
datasource:
  #主库
  master:
    url: jdbc:mysql://localhost:3306/datastone?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: myroot
    password: Mzg...8535933570
    driver-class-name: com.mysql.jdbc.Driver
  #从库
  slave:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: 1666188122
    driver-class-name: org.postgresql.Driver

##mybatis
mybatis:
  mapper-locations: classpath:mappers/*/*.xml
  type-aliases-package: com.alearner.model.*
  check-config-location: true
  #config-location: classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true


#显示输出mybatis的执行sql
logging:
  level:
    com:
      alearner:
        mapper:
          mysql: debug